name: build, test and push multi-arch Docker container images

on:
  pull_request:
    branches: main
    paths:
     - Dockerfile
     - .github/workflows/build-test-and-push.yml
  push:
    branches: main
    paths:
     - Dockerfile
     - .github/workflows/build-test-and-push.yml

env:
  GITHUB_SHA: ${{ github.sha }}
  DOCKERHUB_TARGET_REPO: kathoef/dfjghsdfg

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
     - name: Specify tags
       run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          CALVER_TARGET=${DOCKERHUB_TARGET_REPO}:v${CALVER}-${SHA7}
          LATEST_TARGET=${DOCKERHUB_TARGET_REPO}:latest
          echo "CALVER_TARGET=${CALVER_TARGET}" >> $GITHUB_ENV
          echo "LATEST_TARGET=${LATEST_TARGET}" >> $GITHUB_ENV
     - name: Set up QEMU
       if: ${{ startsWith(github.ref, 'refs/heads/main')}}
       uses: docker/setup-qemu-action@v2
     - name: Set up Buildx
       if: ${{ startsWith(github.ref, 'refs/heads/main')}}
       uses: docker/setup-buildx-action@v2
     - name: Show available Buildx platforms
       if: ${{ startsWith(github.ref, 'refs/heads/main')}}
       run: docker buildx ls
     - name: Checkout Github repository
       uses: actions/checkout@v2
     - name: Build default arch Docker image
       uses: docker/build-push-action@v3
       with:
         load: true # publish as local Docker image
         tags: "${{env.CALVER_TARGET}}, ${{env.LATEST_TARGET}}"
     - name: "Test default arch Docker image: singularity pull"
       run: |
         docker run -v $PWD:/output --rm "${{env.LATEST_TARGET}}" singularity pull alpine_latest.sif docker://alpine:latest
         ls && test -f alpine_latest.sif && rm alpine_latest.sif
     - name: "Test default arch Docker image: singularity build"
       run: |
         echo 'FROM alpine:latest' > Dockerfile
         docker build -f Dockerfile -t local/from_local_build_workflow .
         docker run -v $PWD:/output -v /var/run/docker.sock:/var/run/docker.sock:ro --rm "${{env.LATEST_TARGET}}" singularity build local.sif docker-daemon://local/from_local_build_workflow:latest
         ls && test -f local.sif && rm local.sif
     - name: Login to DockerHub
       if: ${{ startsWith(github.ref, 'refs/heads/main')}}
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_LOGIN_USER }}
        password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}
     - name: Build and push the multi-arch Docker images
       if: ${{ startsWith(github.ref, 'refs/heads/main')}}
       uses: docker/build-push-action@v3
       with:
         platforms: linux/amd64, linux/arm64
         tags: "${{env.CALVER_TARGET}}, ${{env.LATEST_TARGET}}"
         push: true
