name: Docker image tests

on:
  push:
    branches: main
    paths-ignore: Dockerfile
  workflow_dispatch:

env:
  TESTING_IMAGE: kathoef/docker2singularity:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull latest Docker image
      run: docker pull ${{env.TESTING_IMAGE}}
    - name: Test singularity pull
      run: |
       docker run -v $PWD:/output --rm ${{env.TESTING_IMAGE}} singularity pull alpine_latest.sif docker://alpine:latest
       ls; test -f alpine_latest.sif
    - name: Test singularity build from localhost
      run: |
       echo 'FROM alpine:latest' > Dockerfile_for_local_build_workflow
       docker build -f Dockerfile_for_local_build_workflow -t localhost/from_local_build_workflow .
       docker run -v $PWD:/output -v /var/run/docker.sock:/var/run/docker.sock --rm ${{env.TESTING_IMAGE}} singularity build localhost.sif docker-daemon://localhost/from_local_build_workflow:latest
       ls; test -f localhost.sif
